// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/config"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/directory"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/lifecyclesignaler"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/modeselector"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/orchestrator"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/filesystem/files"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/globalmatlab"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/globalmatlab/matlabrootselector"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/globalmatlab/matlabstartingdirselector"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/globalmatlab/vmcrootselector"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/logger"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/localmatlabsession"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/localmatlabsession/directorymanager"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/localmatlabsession/directorymanager/matlabfiles"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/localmatlabsession/processdetails"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/localmatlabsession/processlauncher"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/matlablocator"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/matlablocator/matlabroot"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/matlablocator/matlabversion"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabsessionclient"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabsessionstore"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/resources/codingguidelines"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/resources/vmcblockhelp"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/server"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/server/configurator"
	evalmatlabcode2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/multisession/evalmatlabcode"
	listavailablematlabs2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/multisession/listavailablematlabs"
	startmatlabsession2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/multisession/startmatlabsession"
	stopmatlabsession2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/multisession/stopmatlabsession"
	checkmatlabcode2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/singlesession/checkmatlabcode"
	detectmatlabtoolboxes2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/singlesession/detectmatlabtoolboxes"
	evalmatlabcode3 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/singlesession/evalmatlabcode"
	queryvmcblockhelp2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/singlesession/queryvmcblockhelp"
	runmatlabfile2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/singlesession/runmatlabfile"
	runmatlabtestfile2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/singlesession/runmatlabtestfile"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/watchdog"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/watchdog/process"
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	"github.com/matlab/matlab-mcp-core-server/internal/facades/filefacade"
	"github.com/matlab/matlab-mcp-core-server/internal/facades/iofacade"
	"github.com/matlab/matlab-mcp-core-server/internal/facades/osfacade"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/checkmatlabcode"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/detectmatlabtoolboxes"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/evalmatlabcode"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/listavailablematlabs"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/queryvmcblockhelp"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/runmatlabfile"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/runmatlabtestfile"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/startmatlabsession"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/stopmatlabsession"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/utils/pathvalidator"
	"github.com/matlab/matlab-mcp-core-server/internal/utils/httpclientfactory"
	"github.com/matlab/matlab-mcp-core-server/internal/utils/ossignaler"
	"github.com/matlab/matlab-mcp-core-server/internal/utils/oswrapper"
	watchdog2 "github.com/matlab/matlab-mcp-core-server/internal/watchdog"
	"github.com/matlab/matlab-mcp-core-server/internal/watchdog/processhandler"
	"github.com/matlab/matlab-mcp-core-server/internal/watchdog/transport"
)

// Injectors from wire.go:

func InitializeModeSelector() (*modeselector.ModeSelector, error) {
	osFacade := osfacade.New()
	configConfig, err := config.New(osFacade)
	if err != nil {
		return nil, err
	}
	wireWatchdogProcessFactory := newWatchdogProcessFactory()
	wireOrchestratorFactory := newOrchestratorFactory()
	modeSelector := modeselector.New(configConfig, wireWatchdogProcessFactory, wireOrchestratorFactory, osFacade)
	return modeSelector, nil
}

func initializeOrchestrator() (*orchestrator.Orchestrator, error) {
	lifecycleSignaler := lifecyclesignaler.New()
	osFacade := osfacade.New()
	configConfig, err := config.New(osFacade)
	if err != nil {
		return nil, err
	}
	mcpServer := server.NewMCPSDKServer(configConfig)
	factory := files.NewFactory(osFacade)
	directoryDirectory, err := directory.New(configConfig, factory, osFacade)
	if err != nil {
		return nil, err
	}
	loggerFactory, err := logger.NewFactory(configConfig, directoryDirectory, factory, osFacade)
	if err != nil {
		return nil, err
	}
	fileFacade := filefacade.New()
	getter := matlabroot.New(osFacade, fileFacade)
	ioFacade := iofacade.New()
	matlabversionGetter := matlabversion.New(osFacade, ioFacade)
	matlabLocator := matlablocator.New(getter, matlabversionGetter)
	matlabFiles := matlabfiles.New()
	directoryFactory := directorymanager.NewFactory(osFacade, directoryDirectory, matlabFiles)
	processDetails := processdetails.New(osFacade)
	matlabProcessLauncher := processlauncher.New()
	processProcess, err := process.New(osFacade, loggerFactory, directoryDirectory)
	if err != nil {
		return nil, err
	}
	transportFactory := transport.NewFactory()
	watchdogWatchdog := watchdog.New(processProcess, transportFactory, loggerFactory)
	starter := localmatlabsession.NewStarter(directoryFactory, processDetails, matlabProcessLauncher, watchdogWatchdog)
	matlabServices := matlabservices.New(matlabLocator, starter)
	store := matlabsessionstore.New(loggerFactory, lifecycleSignaler)
	httpClientFactory := httpclientfactory.New()
	matlabsessionclientFactory := matlabsessionclient.NewFactory(httpClientFactory)
	matlabManager := matlabmanager.New(matlabServices, store, matlabsessionclientFactory)
	usecase := listavailablematlabs.New(matlabManager)
	tool := listavailablematlabs2.New(loggerFactory, usecase)
	startmatlabsessionUsecase := startmatlabsession.New(matlabManager)
	startmatlabsessionTool := startmatlabsession2.New(loggerFactory, startmatlabsessionUsecase)
	stopmatlabsessionUsecase := stopmatlabsession.New(matlabManager)
	stopmatlabsessionTool := stopmatlabsession2.New(loggerFactory, stopmatlabsessionUsecase)
	pathValidator := pathvalidator.New(osFacade)
	evalmatlabcodeUsecase := evalmatlabcode.New(pathValidator)
	evalmatlabcodeTool := evalmatlabcode2.New(loggerFactory, evalmatlabcodeUsecase, matlabManager)
	matlabRootSelector := matlabrootselector.New(configConfig, matlabManager)
	vmcRootSelector := vmcrootselector.New(configConfig)
	matlabStartingDirSelector := matlabstartingdirselector.New(configConfig, osFacade)
	globalMATLAB := globalmatlab.New(matlabManager, matlabRootSelector, vmcRootSelector, matlabStartingDirSelector)
	tool2 := evalmatlabcode3.New(loggerFactory, evalmatlabcodeUsecase, globalMATLAB)
	checkmatlabcodeUsecase := checkmatlabcode.New(pathValidator)
	checkmatlabcodeTool := checkmatlabcode2.New(loggerFactory, checkmatlabcodeUsecase, globalMATLAB)
	detectmatlabtoolboxesUsecase := detectmatlabtoolboxes.New()
	detectmatlabtoolboxesTool := detectmatlabtoolboxes2.New(loggerFactory, detectmatlabtoolboxesUsecase, globalMATLAB)
	runmatlabfileUsecase := runmatlabfile.New(pathValidator)
	runmatlabfileTool := runmatlabfile2.New(loggerFactory, runmatlabfileUsecase, globalMATLAB)
	runmatlabtestfileUsecase := runmatlabtestfile.New(pathValidator)
	runmatlabtestfileTool := runmatlabtestfile2.New(loggerFactory, runmatlabtestfileUsecase, globalMATLAB)
	queryvmcblockhelpUsecase := queryvmcblockhelp.New()
	queryvmcblockhelpTool := queryvmcblockhelp2.New(loggerFactory, queryvmcblockhelpUsecase)
	resource, err := codingguidelines.New(loggerFactory)
	if err != nil {
		return nil, err
	}
	vmcblockhelpResource, err := vmcblockhelp.New(loggerFactory)
	if err != nil {
		return nil, err
	}
	configuratorConfigurator := configurator.New(configConfig, tool, startmatlabsessionTool, stopmatlabsessionTool, evalmatlabcodeTool, tool2, checkmatlabcodeTool, detectmatlabtoolboxesTool, runmatlabfileTool, runmatlabtestfileTool, queryvmcblockhelpTool, resource, vmcblockhelpResource)
	serverServer, err := server.New(mcpServer, loggerFactory, lifecycleSignaler, configuratorConfigurator)
	if err != nil {
		return nil, err
	}
	osSignaler := ossignaler.New()
	orchestratorOrchestrator := orchestrator.New(lifecycleSignaler, configConfig, serverServer, watchdogWatchdog, loggerFactory, osSignaler, globalMATLAB, directoryDirectory)
	return orchestratorOrchestrator, nil
}

func initializeWatchdog() (*watchdog2.Watchdog, error) {
	osFacade := osfacade.New()
	configConfig, err := config.New(osFacade)
	if err != nil {
		return nil, err
	}
	factory := files.NewFactory(osFacade)
	directoryDirectory, err := directory.New(configConfig, factory, osFacade)
	if err != nil {
		return nil, err
	}
	loggerFactory, err := logger.NewFactory(configConfig, directoryDirectory, factory, osFacade)
	if err != nil {
		return nil, err
	}
	osWrapper := oswrapper.New(osFacade)
	processHandler := processhandler.New(osWrapper)
	osSignaler := ossignaler.New()
	transportFactory := transport.NewFactory()
	watchdogWatchdog := watchdog2.New(loggerFactory, osFacade, processHandler, osSignaler, transportFactory)
	return watchdogWatchdog, nil
}

// wire.go:

type orchestratorFactory struct{}

func newOrchestratorFactory() *orchestratorFactory {
	return &orchestratorFactory{}
}

func (f *orchestratorFactory) Create() (entities.Mode, error) {
	return initializeOrchestrator()
}

type watchdogProcessFactory struct{}

func newWatchdogProcessFactory() *watchdogProcessFactory {
	return &watchdogProcessFactory{}
}

func (f *watchdogProcessFactory) Create() (entities.Mode, error) {
	return initializeWatchdog()
}
