// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfig creates a new instance of MockConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfig {
	mock := &MockConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfig is an autogenerated mock type for the Config type
type MockConfig struct {
	mock.Mock
}

type MockConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfig) EXPECT() *MockConfig_Expecter {
	return &MockConfig_Expecter{mock: &_m.Mock}
}

// BaseDir provides a mock function for the type MockConfig
func (_mock *MockConfig) BaseDir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BaseDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_BaseDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BaseDir'
type MockConfig_BaseDir_Call struct {
	*mock.Call
}

// BaseDir is a helper method to define mock.On call
func (_e *MockConfig_Expecter) BaseDir() *MockConfig_BaseDir_Call {
	return &MockConfig_BaseDir_Call{Call: _e.mock.On("BaseDir")}
}

func (_c *MockConfig_BaseDir_Call) Run(run func()) *MockConfig_BaseDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_BaseDir_Call) Return(s string) *MockConfig_BaseDir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_BaseDir_Call) RunAndReturn(run func() string) *MockConfig_BaseDir_Call {
	_c.Call.Return(run)
	return _c
}
