// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockFilenameFactory creates a new instance of MockFilenameFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilenameFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilenameFactory {
	mock := &MockFilenameFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFilenameFactory is an autogenerated mock type for the FilenameFactory type
type MockFilenameFactory struct {
	mock.Mock
}

type MockFilenameFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFilenameFactory) EXPECT() *MockFilenameFactory_Expecter {
	return &MockFilenameFactory_Expecter{mock: &_m.Mock}
}

// CreateFileWithUniqueSuffix provides a mock function for the type MockFilenameFactory
func (_mock *MockFilenameFactory) CreateFileWithUniqueSuffix(baseName string, ext string) (string, string, error) {
	ret := _mock.Called(baseName, ext)

	if len(ret) == 0 {
		panic("no return value specified for CreateFileWithUniqueSuffix")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, string, error)); ok {
		return returnFunc(baseName, ext)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(baseName, ext)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) string); ok {
		r1 = returnFunc(baseName, ext)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = returnFunc(baseName, ext)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockFilenameFactory_CreateFileWithUniqueSuffix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFileWithUniqueSuffix'
type MockFilenameFactory_CreateFileWithUniqueSuffix_Call struct {
	*mock.Call
}

// CreateFileWithUniqueSuffix is a helper method to define mock.On call
//   - baseName string
//   - ext string
func (_e *MockFilenameFactory_Expecter) CreateFileWithUniqueSuffix(baseName interface{}, ext interface{}) *MockFilenameFactory_CreateFileWithUniqueSuffix_Call {
	return &MockFilenameFactory_CreateFileWithUniqueSuffix_Call{Call: _e.mock.On("CreateFileWithUniqueSuffix", baseName, ext)}
}

func (_c *MockFilenameFactory_CreateFileWithUniqueSuffix_Call) Run(run func(baseName string, ext string)) *MockFilenameFactory_CreateFileWithUniqueSuffix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFilenameFactory_CreateFileWithUniqueSuffix_Call) Return(s string, s1 string, err error) *MockFilenameFactory_CreateFileWithUniqueSuffix_Call {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *MockFilenameFactory_CreateFileWithUniqueSuffix_Call) RunAndReturn(run func(baseName string, ext string) (string, string, error)) *MockFilenameFactory_CreateFileWithUniqueSuffix_Call {
	_c.Call.Return(run)
	return _c
}
