// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockApplicationDirectory creates a new instance of MockApplicationDirectory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApplicationDirectory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApplicationDirectory {
	mock := &MockApplicationDirectory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockApplicationDirectory is an autogenerated mock type for the ApplicationDirectory type
type MockApplicationDirectory struct {
	mock.Mock
}

type MockApplicationDirectory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApplicationDirectory) EXPECT() *MockApplicationDirectory_Expecter {
	return &MockApplicationDirectory_Expecter{mock: &_m.Mock}
}

// CreateSubDir provides a mock function for the type MockApplicationDirectory
func (_mock *MockApplicationDirectory) CreateSubDir(pattern string) (string, error) {
	ret := _mock.Called(pattern)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubDir")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(pattern)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(pattern)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(pattern)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockApplicationDirectory_CreateSubDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubDir'
type MockApplicationDirectory_CreateSubDir_Call struct {
	*mock.Call
}

// CreateSubDir is a helper method to define mock.On call
//   - pattern string
func (_e *MockApplicationDirectory_Expecter) CreateSubDir(pattern interface{}) *MockApplicationDirectory_CreateSubDir_Call {
	return &MockApplicationDirectory_CreateSubDir_Call{Call: _e.mock.On("CreateSubDir", pattern)}
}

func (_c *MockApplicationDirectory_CreateSubDir_Call) Run(run func(pattern string)) *MockApplicationDirectory_CreateSubDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockApplicationDirectory_CreateSubDir_Call) Return(s string, err error) *MockApplicationDirectory_CreateSubDir_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockApplicationDirectory_CreateSubDir_Call) RunAndReturn(run func(pattern string) (string, error)) *MockApplicationDirectory_CreateSubDir_Call {
	_c.Call.Return(run)
	return _c
}
