// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDirectory creates a new instance of MockDirectory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDirectory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDirectory {
	mock := &MockDirectory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDirectory is an autogenerated mock type for the Directory type
type MockDirectory struct {
	mock.Mock
}

type MockDirectory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDirectory) EXPECT() *MockDirectory_Expecter {
	return &MockDirectory_Expecter{mock: &_m.Mock}
}

// RecordToLogger provides a mock function for the type MockDirectory
func (_mock *MockDirectory) RecordToLogger(logger entities.Logger) {
	_mock.Called(logger)
	return
}

// MockDirectory_RecordToLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordToLogger'
type MockDirectory_RecordToLogger_Call struct {
	*mock.Call
}

// RecordToLogger is a helper method to define mock.On call
//   - logger entities.Logger
func (_e *MockDirectory_Expecter) RecordToLogger(logger interface{}) *MockDirectory_RecordToLogger_Call {
	return &MockDirectory_RecordToLogger_Call{Call: _e.mock.On("RecordToLogger", logger)}
}

func (_c *MockDirectory_RecordToLogger_Call) Run(run func(logger entities.Logger)) *MockDirectory_RecordToLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.Logger
		if args[0] != nil {
			arg0 = args[0].(entities.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDirectory_RecordToLogger_Call) Return() *MockDirectory_RecordToLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDirectory_RecordToLogger_Call) RunAndReturn(run func(logger entities.Logger)) *MockDirectory_RecordToLogger_Call {
	_c.Run(run)
	return _c
}
