// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockFilenameFactory creates a new instance of MockFilenameFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilenameFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilenameFactory {
	mock := &MockFilenameFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFilenameFactory is an autogenerated mock type for the FilenameFactory type
type MockFilenameFactory struct {
	mock.Mock
}

type MockFilenameFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFilenameFactory) EXPECT() *MockFilenameFactory_Expecter {
	return &MockFilenameFactory_Expecter{mock: &_m.Mock}
}

// FilenameWithSuffix provides a mock function for the type MockFilenameFactory
func (_mock *MockFilenameFactory) FilenameWithSuffix(fileName string, ext string, suffix string) string {
	ret := _mock.Called(fileName, ext, suffix)

	if len(ret) == 0 {
		panic("no return value specified for FilenameWithSuffix")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = returnFunc(fileName, ext, suffix)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockFilenameFactory_FilenameWithSuffix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilenameWithSuffix'
type MockFilenameFactory_FilenameWithSuffix_Call struct {
	*mock.Call
}

// FilenameWithSuffix is a helper method to define mock.On call
//   - fileName string
//   - ext string
//   - suffix string
func (_e *MockFilenameFactory_Expecter) FilenameWithSuffix(fileName interface{}, ext interface{}, suffix interface{}) *MockFilenameFactory_FilenameWithSuffix_Call {
	return &MockFilenameFactory_FilenameWithSuffix_Call{Call: _e.mock.On("FilenameWithSuffix", fileName, ext, suffix)}
}

func (_c *MockFilenameFactory_FilenameWithSuffix_Call) Run(run func(fileName string, ext string, suffix string)) *MockFilenameFactory_FilenameWithSuffix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFilenameFactory_FilenameWithSuffix_Call) Return(s string) *MockFilenameFactory_FilenameWithSuffix_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockFilenameFactory_FilenameWithSuffix_Call) RunAndReturn(run func(fileName string, ext string, suffix string) string) *MockFilenameFactory_FilenameWithSuffix_Call {
	_c.Call.Return(run)
	return _c
}
